version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
      - npm test
  post_build:
    commands:
      - aws s3 sync build/ s3://$S3_BUCKET
artifacts:
  files:
    - '**/*'
  base-directory: 'build'